### PR TITLE
Support Laravel 11

### PR DESCRIPTION
**Pull request by michaeldyrynda**
Bumps dependencies to support Laravel 11, along with CI workflow changes.

### CODE REVIEW

**Comment by michaeldyrynda** [comment]
This possibly requires more thought as to how you want to approach tagging the next version @lepikhinb, given that Laravel 11 will require PHP 8.2.

Happy to make the relevant changes based on what you want to do, though.

**Comment by lepikhinb** [comment]
@michaeldyrynda let’s tag the minor version 👌🏻

Thank you for the help!

**Comment by bobbypiper** [comment]
@lepikhinb Any chance of this PR being merged now L11 has been released? 

Happy to support if you need any help :)

**Comment by 1CAMOU** [comment]
would be great if it would also use Ziggy v2

**Pull request merged**
